apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: config-pipeline
spec:
  description: >-
    This pipeline will import the router-ca from Openshift-Ingress-Operator namespace,
    create the Openshift/Gitea/Quay Keycloak Clients,configure the SSO integration to
    Gitea and Quay. In order to modify the individual variables in the pipeline, you
    can create a params field and reference all the values in the pipeline resource.
    The easier way is to edit the pipeline through Openshift and click on the corresponding
    task and modify your variables that way.
  tasks:
    - name: oc-create-admin-secret
      params:
        - name: VERSION
          value: '4.6'
        - name: USERNAME
          value: kubeadmin
        - name: PASSWORD
          value: D4tTL-hJYdy-qe36Y-okTwh
        - name: NAMESPACE
          value: dso
      taskRef:
        kind: Task
        name: oc-create-admin-secret
    - name: oc-copy-router-ca
      params:
        - name: VERSION
          value: '4.6'
      runAfter:
        - oc-create-admin-secret
      taskRef:
        kind: Task
        name: oc-copy-router-ca
    - name: create-ocp-keycloak-client
      params:
        - name: DOMAIN
          value: crc.testing
        - name: APPS_SUBDOMAIN
          value: apps-crc.testing
        - name: CLIENT_NAME
          value: openshift
        - name: CLIENT_ID
          value: openshift
        - name: CLIENT_SECRET
          value: openshift
        - name: VERSION
          value: '4.6'
      runAfter:
        - oc-copy-router-ca
      taskRef:
        kind: Task
        name: create-ocp-keycloak-client
    - name: create-gitea-keycloak-client
      params:
        - name: DOMAIN
          value: 'https://gitea-dso.apps-crc.testing'
        - name: CLIENT_NAME
          value: gitea
        - name: CLIENT_ID
          value: gitea
        - name: CLIENT_SECRET
          value: openshift
        - name: VERSION
          value: '4.6'
      runAfter:
        - oc-copy-router-ca
      taskRef:
        kind: Task
        name: create-gitea-keycloak-client
    - name: patch-gitea-deployment-with-openshift-certs
      params:
        - name: OPENSHIFT_CERT_SECRET
          value: router-ca
        - name: VERSION
          value: '4.6'
      runAfter:
        - oc-copy-router-ca
      taskRef:
        kind: Task
        name: patch-gitea-deployment-with-openshift-certs
    - name: create-oidc-in-gitea
      params:
        - name: AUTH_NAME
          value: keycloakoidc
        - name: PROVIDER
          value: openidConnect
        - name: PROVIDER_ID
          value: gitea
        - name: PROVIDER_SECRET
          value: openshift
        - name: PROVIDER_URL
          value: 'https://keycloak-dso.apps-crc.testing'
        - name: PROVIDER_REALM
          value: openshift-realm
        - name: VERSION
          value: '4.6'
      runAfter:
        - patch-gitea-deployment-with-openshift-certs
      taskRef:
        kind: Task
        name: create-oidc-in-gitea
