apiVersion: v1
kind: List
items:
# Subscription to trigger OLM installation
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: quay-operator
  spec:
    channel: quay-v3.4
    installPlanApproval: Automatic
    name: quay-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: quay-operator.v3.4.3
# Secret required to pull from quay.io
- apiVersion: v1
  kind: Secret
  metadata:
    name: dummy-pull-secret
  type: kubernetes.io/dockerconfigjson
  data:
    .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjbVZrYUdGMEszRjFZWGs2VHpneFYxTklVbE5LVWpFMFZVRmFRa3MxTkVkUlNFcFRNRkF4VmpSRFRGZEJTbFl4V0RKRE5GTkVOMHRQTlRsRFVUbE9NMUpGTVRJMk1USllWVEZJVWc9PSIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9