apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: quay-ecosystem
spec:
  components:
    - kind: clair
      managed: true
    - kind: postgres
      managed: true
    - kind: redis
      managed: true
    - kind: route
      managed: true
    - kind: mirror
      managed: false
    - kind: objectstorage
      managed: false
    - kind: horizontalpodautoscaler
      managed: false
  configBundleSecret: custom-quay-config-bundle
